apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
  namespace: tracing-test
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        service: backend
    spec:
      containers:
        - env:
            - name: DEMO_APP_ADDR
              value: 0.0.0.0:8000
            - name: DEMO_REDIS_ADDR
              value: redis:6379
#          image: gcr.io/sq-stage-94587/tracing-test-backend:2-tracing
          image: gcr.io/sq-stage-94587/tracing-test-backend:agent
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
