apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: tracing-test
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
        - env:
            - name: BACKEND_SVC_URL
              value: backend:8000
            - name: FRONTEND_APP_ADDR
              value: 0.0.0.0:8080
#          image: gcr.io/sq-stage-94587/tracing-test-frontend:2-tracing
          image: gcr.io/sq-stage-94587/tracing-test-frontend:agent
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
