apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: tracing-wo-agent 
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
        - env:
            - name: BACKEND_SVC_URL
              value: backend:8000
            - name: FRONTEND_APP_ADDR
              value: 0.0.0.0:8080
            - name: JAEGER_ENDPOINT_URL
              value: http://jaeger-collector.internal-tools.svc:14268/api/traces
          image: gcr.io/sq-stage-94587/tracing-test-frontend:2-tracing
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
