apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: tracing-wo-agent 
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: frontend
